export const orderData = [
  {
    id: 1,
    orderCode: "ORD001",
    customer: "John Smith",
    purchaseDate: "2024-03-18",
    status: "Pending",
    deliveryDate: new Date(),
  },
  {
    id: 2,
    orderCode: "ORD002",
    customer: "Alice Johnson",
    purchaseDate: "2024-03-19",
    status: "Processing",
    deliveryDate: "2024-03-20",
  },
  {
    id: 3,
    orderCode: "ORD003",
    customer: "Michael Brown",
    purchaseDate: "2024-03-20",
    status: "Delivered",
    deliveryDate: new Date(),
  },
  {
    id: 4,
    orderCode: "ORD004",
    customer: "Emily Davis",
    purchaseDate: "2024-03-18",
    status: "Pending",
    deliveryDate: new Date(),
  },
  {
    id: 5,
    orderCode: "ORD005",
    customer: "Emma Wilson",
    purchaseDate: "2024-03-21",
    status: "Processing",
    deliveryDate: "2024-03-23",
  },
  {
    id: 6,
    orderCode: "ORD006",
    customer: "James Anderson",
    purchaseDate: "2024-03-22",
    status: "Pending",
    deliveryDate: new Date(),
  },
  {
    id: 7,
    orderCode: "ORD007",
    customer: "Olivia Martinez",
    purchaseDate: "2024-03-23",
    status: "Delivered",
    deliveryDate: "2024-03-25",
  },
  {
    id: 8,
    orderCode: "ORD008",
    customer: "Daniel Taylor",
    purchaseDate: "2024-03-24",
    status: "Processing",
    deliveryDate: new Date(),
  },
  {
    id: 9,
    orderCode: "ORD009",
    customer: "Sophia Wilson",
    purchaseDate: "2024-03-25",
    status: "Pending",
    deliveryDate: new Date(),
  },
  {
    id: 10,
    orderCode: "ORD010",
    customer: "Liam Thomas",
    purchaseDate: "2024-03-26",
    status: "Delivered",
    deliveryDate: new Date(),
  },
];

export const productData = [
  {
    id: 1,
    name: "Laptop",
    category: "Electronics",
    price: 999.99,
    stockQuantity: 10,
  },
  {
    id: 2,
    name: "Smartphone",
    category: "Electronics",
    price: 699.99,
    stockQuantity: 15,
  },
  {
    id: 3,
    name: "Headphones",
    category: "Electronics",
    price: 99.99,
    stockQuantity: 20,
  },
  {
    id: 4,
    name: "T-shirt",
    category: "Clothing",
    price: 19.99,
    stockQuantity: 30,
  },
  {
    id: 5,
    name: "Jeans",
    category: "Clothing",
    price: 39.99,
    stockQuantity: 25,
  },
  {
    id: 6,
    name: "Sneakers",
    category: "Footwear",
    price: 59.99,
    stockQuantity: 20,
  },
  {
    id: 7,
    name: "Backpack",
    category: "Accessories",
    price: 49.99,
    stockQuantity: 15,
  },
  {
    id: 8,
    name: "Watch",
    category: "Accessories",
    price: 199.99,
    stockQuantity: 10,
  },
  {
    id: 9,
    name: "Sunglasses",
    category: "Accessories",
    price: 79.99,
    stockQuantity: 15,
  },
  {
    id: 10,
    name: "Desk",
    category: "Furniture",
    price: 299.99,
    stockQuantity: 5,
  },
  {
    id: 11,
    name: "Chair",
    category: "Furniture",
    price: 199.99,
    stockQuantity: 8,
  },
  {
    id: 12,
    name: "Table",
    category: "Furniture",
    price: 149.99,
    stockQuantity: 10,
  },
];
